apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: receiver
  annotations:
    autoscaling.knative.dev/maxScale: "10"
spec:
  template:
    spec:
      containerConcurrency: 20
      containers:
      - image: gcr.io/stardust-skyhook/receiver:v1beta1
        resources:
          limits:
            cpu: "1"
            memory: 128Mi
        env:
        - name: WEBHOOK_DOCS_URL
          value: https://devmode.cloud/docs/webhooks.html
        - name: RECEIVER_PROJECT_ID
          value: stardust-skyhook
        - name: RECEIVER_FRAME_COLLECTION
          value: /users/webhooks/services/processor/frames
