apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: receiver
  annotations:
    autoscaling.knative.dev/maxScale: "10"
spec:
  template:
    spec:
      containerConcurrency: 20
      containers:
      - image: gcr.io/stardust-skyhook/receiver:v1alpha4
        resources:
          limits:
            cpu: "1"
            memory: 128Mi
        env:
        - name: LOG_LEVEL
          value: debug
